[package]
name = "cmd-wrappers-macro"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.11"
itertools = "0.14.0"
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.100", features = ["extra-traits", "full"] }
