name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/setup-rust@v1.7.0
        with:
          rust-version: stable
          components: clippy
      
      - name: Cache cargo registry
        uses: actions/cache@v3
        with: 
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: cargo fetch

      - name: Build project
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose --all-features

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings


